# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d7a416e46a7ad2c9c19a5ceb52adc52f20076503f51fa04ebea181c458460d411f6f2bcd5179972a7847c808d994700bbf7e95f667ddbb84c8f83202cddfcc5

test:
  secret_key_base: 5710a0f547a0f49c748f2cd6c48bfed2b11f133d0d68a5fa7a5365520a679a733f203b4f2650a86e16940085542302cbb21f7e47e5a023b5cf6016cb019508cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
