require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe OcorrenciasController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Ocorrencia. As you add validations to Ocorrencia, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OcorrenciasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all ocorrencias as @ocorrencias" do
      ocorrencia = Ocorrencia.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:ocorrencias)).to eq([ocorrencia])
    end
  end

  describe "GET show" do
    it "assigns the requested ocorrencia as @ocorrencia" do
      ocorrencia = Ocorrencia.create! valid_attributes
      get :show, {:id => ocorrencia.to_param}, valid_session
      expect(assigns(:ocorrencia)).to eq(ocorrencia)
    end
  end

  describe "GET new" do
    it "assigns a new ocorrencia as @ocorrencia" do
      get :new, {}, valid_session
      expect(assigns(:ocorrencia)).to be_a_new(Ocorrencia)
    end
  end

  describe "GET edit" do
    it "assigns the requested ocorrencia as @ocorrencia" do
      ocorrencia = Ocorrencia.create! valid_attributes
      get :edit, {:id => ocorrencia.to_param}, valid_session
      expect(assigns(:ocorrencia)).to eq(ocorrencia)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Ocorrencia" do
        expect {
          post :create, {:ocorrencia => valid_attributes}, valid_session
        }.to change(Ocorrencia, :count).by(1)
      end

      it "assigns a newly created ocorrencia as @ocorrencia" do
        post :create, {:ocorrencia => valid_attributes}, valid_session
        expect(assigns(:ocorrencia)).to be_a(Ocorrencia)
        expect(assigns(:ocorrencia)).to be_persisted
      end

      it "redirects to the created ocorrencia" do
        post :create, {:ocorrencia => valid_attributes}, valid_session
        expect(response).to redirect_to(Ocorrencia.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ocorrencia as @ocorrencia" do
        post :create, {:ocorrencia => invalid_attributes}, valid_session
        expect(assigns(:ocorrencia)).to be_a_new(Ocorrencia)
      end

      it "re-renders the 'new' template" do
        post :create, {:ocorrencia => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested ocorrencia" do
        ocorrencia = Ocorrencia.create! valid_attributes
        put :update, {:id => ocorrencia.to_param, :ocorrencia => new_attributes}, valid_session
        ocorrencia.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested ocorrencia as @ocorrencia" do
        ocorrencia = Ocorrencia.create! valid_attributes
        put :update, {:id => ocorrencia.to_param, :ocorrencia => valid_attributes}, valid_session
        expect(assigns(:ocorrencia)).to eq(ocorrencia)
      end

      it "redirects to the ocorrencia" do
        ocorrencia = Ocorrencia.create! valid_attributes
        put :update, {:id => ocorrencia.to_param, :ocorrencia => valid_attributes}, valid_session
        expect(response).to redirect_to(ocorrencia)
      end
    end

    describe "with invalid params" do
      it "assigns the ocorrencia as @ocorrencia" do
        ocorrencia = Ocorrencia.create! valid_attributes
        put :update, {:id => ocorrencia.to_param, :ocorrencia => invalid_attributes}, valid_session
        expect(assigns(:ocorrencia)).to eq(ocorrencia)
      end

      it "re-renders the 'edit' template" do
        ocorrencia = Ocorrencia.create! valid_attributes
        put :update, {:id => ocorrencia.to_param, :ocorrencia => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ocorrencia" do
      ocorrencia = Ocorrencia.create! valid_attributes
      expect {
        delete :destroy, {:id => ocorrencia.to_param}, valid_session
      }.to change(Ocorrencia, :count).by(-1)
    end

    it "redirects to the ocorrencias list" do
      ocorrencia = Ocorrencia.create! valid_attributes
      delete :destroy, {:id => ocorrencia.to_param}, valid_session
      expect(response).to redirect_to(ocorrencias_url)
    end
  end

end
